// Build step: read SUPABASE_URL + SUPABASE_ANON_KEY from env and emit
// js/config.runtime.js, which is loaded by every page BEFORE app.js.
//
// Run:  SUPABASE_URL=... SUPABASE_ANON_KEY=... node build-config.js
//
// In CI (Cloudflare Pages), set the same env vars in the Pages project
// and add `node build-config.js` to the build command.
//
// After running, the script writes js/config.runtime.js and the rest of
// the app loads it instead of config.js. config.js falls back to
// reading window.__SUPABASE_URL__ which the runtime file populates.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const url = process.env.SUPABASE_URL;
const anon = process.env.SUPABASE_ANON_KEY;
if (!url || !anon) {
  console.error('SUPABASE_URL and SUPABASE_ANON_KEY must be set.');
  process.exit(1);
}

const out = `// Generated by build-config.js — do not edit.
window.__SUPABASE_URL__ = ${JSON.stringify(url)};
window.__SUPABASE_ANON_KEY__ = ${JSON.stringify(anon)};
`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, 'js', 'config.runtime.js'), out);
console.log('Wrote js/config.runtime.js');